# Discussion Section 1: Prey species in the California drylands
### This discussion section will go through preliminary data exploration for a real-world dataset about animal observations in the California drylands

## 1. About the data
Description: The dataset contains cleaned GBIF occurrence records and associated climate and environmental data for all arthropod prey of the species in California drylands as identified in Lortie et al. (2023)
Citation: Rachel King, Jenna Braun, Michael Westphal, & CJ Lortie. (2023). Compiled occurrence records for prey items of listed species found in California drylands with associated environmental data. Knowledge Network for Biocomplexity. [doi:10.5063/F1VM49RH](doi:10.5063/F1VM49RH).
Date of access: Thursday, October 1, 2026
Link: [Archive]()

In [1]:
import os
import pandas as pd

## 2. Metadata exploration

In [2]:
# Access metadata from repository

pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A3baf7289-bf90-4db3-ad11-58785c09b26e')

,attribute,description
0,class,taxonomic class of observed organism
1,order,taxonomic order of observed organism
2,family,taxonomic family of observed organism
3,genus,genus name
4,species,full latin binomial name
5,lat,latitude of occurrence record in decimal degrees
6,long,longitude of occurrence record in decimal degrees
7,eventDate,date and time of observation in YYYY-MM-DD HH:...
8,day,day of the month of observation
9,month,month of observation
10,year,observation year
11,institutionCode,institution code provided by GBIF (www.gbif.org)
12,coordinateUncertaintyInMeters,coordinate uncertainty in meters; NA indicate ...
13,basisOfRecord,"type of record provided by GBIF; one of ""HUMAN..."
14,individualCount,number of individuals (if provided) observed f...
15,datasetKey,unique dataset key provided by GBIF
16,bio1,"annual mean temperature (degrees Celsius, x10)"
17,bio10,mean temperature of warmest quarter (degrees C...
18,bio11,mean temperature of coldest quarter (degrees C...
19,bio12,annual precipitation (millimeters (mm))
20,bio13,precipitation of wettest month (mm)
21,bio14,precipitation of driest month (mm)
22,bio15,precipitation seasonality (percent)
23,bio16,precipitation of wettest quarter (mm)
24,bio17,precipitation of driest quarter (mm)
25,bio18,precipitation of warmest quarter (mm)
26,bio19,precipitation of coldest quarter (mm)
27,bio2,"annual mean diurnal range (degrees Celsius, x10)"
28,bio3,isothermality (percent)
29,bio4,"temperature seasonality (degrees Celsius, x100)"
30,bio5,max temperature of warmest month (degrees Cels...
31,bio6,min temperature of coldest month (degrees Cels...
32,bio7,"annual temperature range (degrees Celsius, x10)"
33,bio8,mean temperature of wettest month (degrees Cel...
34,bio9,mean temperature of driest quarter (degrees Ce...
35,dist,distance to the nearest major road (kilometers...
36,dem90_hf,elevation (meters); data from the National Ele...
37,lc_class,landcover classification from the University o...
38,ndvi,the mean normalized difference vegetation inde...
39,notes,all bioX variables are from the WorldClim data...

## 3. Data Loading

In [3]:
# Load data

fp = os.path.join('data', 'arth_occurrences_with_env.csv')
prey = pd.read_csv(fp)
print(prey.shape)
prey.head(3)

(11817, 40)

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664

## 4. Look at your data

In [4]:
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11812,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.582359,-117.130409,2022-04-06T17:45:07Z,6.0,4.0,...,2938.296631,251.787964,75.391914,176.396042,135.899994,201.051651,1.481260,3.334348,urban,2509.291504
11813,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.235500,-117.280700,2016-04-28T06:45:00Z,28.0,4.0,...,3478.261719,275.912842,62.300415,213.612412,130.638260,209.373581,1.022442,95.028740,urban,3148.228271
11814,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.713627,-117.551982,2017-05-28T12:28:00Z,28.0,5.0,...,5090.127930,301.096008,21.714203,279.381805,89.029083,207.946884,7.999103,1150.327515,grassland,6280.781738
11815,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.283060,-116.152294,2019-03-09T00:00:00Z,9.0,3.0,...,6963.564941,404.882080,39.630005,365.252075,135.455856,230.889984,0.908103,324.845062,barren,925.266907
11816,Insecta,Coleoptera,Tenebrionidae,Eleodes,Eleodes acuticauda,33.598366,-117.820217,2020-05-02T10:09:00Z,2.0,5.0,...,3333.221680,272.416626,65.048866,207.367767,129.048874,203.714371,1.281493,186.832230,urban,4851.400000

In [5]:
pd.set_option("display.max_columns", None)

In [6]:
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11812,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.582359,-117.130409,2022-04-06T17:45:07Z,6.0,4.0,2022,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11813,168.864929,209.279877,132.899994,217.126556,43.935062,0.186721,88.170128,122.583405,3.186721,5.864936,109.776558,91.074677,51.186722,2938.296631,251.787964,75.391914,176.396042,135.899994,201.051651,1.481260,3.334348,urban,2509.291504
11813,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.235500,-117.280700,2016-04-28T06:45:00Z,28.0,4.0,2016,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11814,168.944000,217.027542,127.524216,302.635620,59.679543,1.225997,86.732315,166.990814,6.451993,12.225997,155.940826,115.709236,53.982101,3478.261719,275.912842,62.300415,213.612412,130.638260,209.373581,1.022442,95.028740,urban,3148.228271
11814,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.713627,-117.551982,2017-05-28T12:28:00Z,28.0,5.0,2017,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11815,143.129761,214.728897,86.312645,703.884155,134.159149,3.000000,87.217995,382.778320,12.450000,25.301556,367.643189,138.747574,49.332005,5090.127930,301.096008,21.714203,279.381805,89.029083,207.946884,7.999103,1150.327515,grassland,6280.781738
11815,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.283060,-116.152294,2019-03-09T00:00:00Z,9.0,3.0,2019,iNaturalist,199.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11816,207.828796,298.661102,123.264259,152.645325,24.174152,0.571964,57.834797,66.522461,10.265621,23.066544,64.668320,172.413681,46.717823,6963.564941,404.882080,39.630005,365.252075,135.455856,230.889984,0.908103,324.845062,barren,925.266907
11816,Insecta,Coleoptera,Tenebrionidae,Eleodes,Eleodes acuticauda,33.598366,-117.820217,2020-05-02T10:09:00Z,2.0,5.0,2020,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11817,165.278626,211.716537,126.672401,344.240540,69.188713,1.000000,89.915398,194.495606,6.277601,11.308143,186.073731,113.556824,54.437012,3333.221680,272.416626,65.048866,207.367767,129.048874,203.714371,1.281493,186.832230,urban,4851.400000

`pd.set_option("display.max_columns", None)` makes it so you can see all the columns, even if there are a ton. It prevents the middle chunk from being hidden for brevity.