# Discussion Section 1: Prey species in the California drylands
### This discussion section will go through preliminary data exploration for a real-world dataset about animal observations in the California drylands

## 1. About the data
Description: The dataset contains cleaned GBIF occurrence records and associated climate and environmental data for all arthropod prey of the species in California drylands as identified in Lortie et al. (2023)
Citation: Rachel King, Jenna Braun, Michael Westphal, & CJ Lortie. (2023). Compiled occurrence records for prey items of listed species found in California drylands with associated environmental data. Knowledge Network for Biocomplexity. [doi:10.5063/F1VM49RH](doi:10.5063/F1VM49RH).
Date of access: Thursday, October 1, 2026
Link: [Archive]()

In [1]:
import os
import pandas as pd

## 2. Metadata exploration

In [2]:
# Access metadata from repository

pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A3baf7289-bf90-4db3-ad11-58785c09b26e')

,attribute,description
0,class,taxonomic class of observed organism
1,order,taxonomic order of observed organism
2,family,taxonomic family of observed organism
3,genus,genus name
4,species,full latin binomial name
5,lat,latitude of occurrence record in decimal degrees
6,long,longitude of occurrence record in decimal degrees
7,eventDate,date and time of observation in YYYY-MM-DD HH:...
8,day,day of the month of observation
9,month,month of observation
10,year,observation year
11,institutionCode,institution code provided by GBIF (www.gbif.org)
12,coordinateUncertaintyInMeters,coordinate uncertainty in meters; NA indicate ...
13,basisOfRecord,"type of record provided by GBIF; one of ""HUMAN..."
14,individualCount,number of individuals (if provided) observed f...
15,datasetKey,unique dataset key provided by GBIF
16,bio1,"annual mean temperature (degrees Celsius, x10)"
17,bio10,mean temperature of warmest quarter (degrees C...
18,bio11,mean temperature of coldest quarter (degrees C...
19,bio12,annual precipitation (millimeters (mm))
20,bio13,precipitation of wettest month (mm)
21,bio14,precipitation of driest month (mm)
22,bio15,precipitation seasonality (percent)
23,bio16,precipitation of wettest quarter (mm)
24,bio17,precipitation of driest quarter (mm)
25,bio18,precipitation of warmest quarter (mm)
26,bio19,precipitation of coldest quarter (mm)
27,bio2,"annual mean diurnal range (degrees Celsius, x10)"
28,bio3,isothermality (percent)
29,bio4,"temperature seasonality (degrees Celsius, x100)"
30,bio5,max temperature of warmest month (degrees Cels...
31,bio6,min temperature of coldest month (degrees Cels...
32,bio7,"annual temperature range (degrees Celsius, x10)"
33,bio8,mean temperature of wettest month (degrees Cel...
34,bio9,mean temperature of driest quarter (degrees Ce...
35,dist,distance to the nearest major road (kilometers...
36,dem90_hf,elevation (meters); data from the National Ele...
37,lc_class,landcover classification from the University o...
38,ndvi,the mean normalized difference vegetation inde...
39,notes,all bioX variables are from the WorldClim data...

## 3. Data Loading

In [3]:
# Load data

fp = os.path.join('data', 'arth_occurrences_with_env.csv')
prey = pd.read_csv(fp)
print(prey.shape)
prey.head(3)

(11817, 40)

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664

## 4. Look at your data

In [4]:
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11812,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.582359,-117.130409,2022-04-06T17:45:07Z,6.0,4.0,...,2938.296631,251.787964,75.391914,176.396042,135.899994,201.051651,1.481260,3.334348,urban,2509.291504
11813,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.235500,-117.280700,2016-04-28T06:45:00Z,28.0,4.0,...,3478.261719,275.912842,62.300415,213.612412,130.638260,209.373581,1.022442,95.028740,urban,3148.228271
11814,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.713627,-117.551982,2017-05-28T12:28:00Z,28.0,5.0,...,5090.127930,301.096008,21.714203,279.381805,89.029083,207.946884,7.999103,1150.327515,grassland,6280.781738
11815,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.283060,-116.152294,2019-03-09T00:00:00Z,9.0,3.0,...,6963.564941,404.882080,39.630005,365.252075,135.455856,230.889984,0.908103,324.845062,barren,925.266907
11816,Insecta,Coleoptera,Tenebrionidae,Eleodes,Eleodes acuticauda,33.598366,-117.820217,2020-05-02T10:09:00Z,2.0,5.0,...,3333.221680,272.416626,65.048866,207.367767,129.048874,203.714371,1.281493,186.832230,urban,4851.400000

In [5]:
pd.set_option("display.max_columns", None)

In [6]:
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11812,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.582359,-117.130409,2022-04-06T17:45:07Z,6.0,4.0,2022,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11813,168.864929,209.279877,132.899994,217.126556,43.935062,0.186721,88.170128,122.583405,3.186721,5.864936,109.776558,91.074677,51.186722,2938.296631,251.787964,75.391914,176.396042,135.899994,201.051651,1.481260,3.334348,urban,2509.291504
11813,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.235500,-117.280700,2016-04-28T06:45:00Z,28.0,4.0,2016,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11814,168.944000,217.027542,127.524216,302.635620,59.679543,1.225997,86.732315,166.990814,6.451993,12.225997,155.940826,115.709236,53.982101,3478.261719,275.912842,62.300415,213.612412,130.638260,209.373581,1.022442,95.028740,urban,3148.228271
11814,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.713627,-117.551982,2017-05-28T12:28:00Z,28.0,5.0,2017,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11815,143.129761,214.728897,86.312645,703.884155,134.159149,3.000000,87.217995,382.778320,12.450000,25.301556,367.643189,138.747574,49.332005,5090.127930,301.096008,21.714203,279.381805,89.029083,207.946884,7.999103,1150.327515,grassland,6280.781738
11815,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.283060,-116.152294,2019-03-09T00:00:00Z,9.0,3.0,2019,iNaturalist,199.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11816,207.828796,298.661102,123.264259,152.645325,24.174152,0.571964,57.834797,66.522461,10.265621,23.066544,64.668320,172.413681,46.717823,6963.564941,404.882080,39.630005,365.252075,135.455856,230.889984,0.908103,324.845062,barren,925.266907
11816,Insecta,Coleoptera,Tenebrionidae,Eleodes,Eleodes acuticauda,33.598366,-117.820217,2020-05-02T10:09:00Z,2.0,5.0,2020,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11817,165.278626,211.716537,126.672401,344.240540,69.188713,1.000000,89.915398,194.495606,6.277601,11.308143,186.073731,113.556824,54.437012,3333.221680,272.416626,65.048866,207.367767,129.048874,203.714371,1.281493,186.832230,urban,4851.400000

`pd.set_option("display.max_columns", None)` makes it so you can see all the columns, even if there are a ton. It prevents the middle chunk from being hidden for brevity.

## 5. `pd.DataFrame` preliminary exploration

Run each of the following methods for prey in a different cell and write a brief description of what they do as a comment:

head()
tail()
info()
nunique()
For example:

# head()
# returns the first five rows of the data frame

prey.head()
If you’re not sure about what the method does, try looking it up in the pandas.DataFrame documentation.

Check the documentation for head(). If this function has any optional parameters, change the default value to get a different output.
Print each of the following attributes of prey in a different cell and write a brief explanation of what they are as a comment:

shape
columns
dtypes
If you’re not sure about what information the attribute is showing, look it up in the pandas.DataFrame documentation!

check git status -> stage changes -> check git status -> commit with message -> pull -> push changes

In [9]:
print(prey.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11817 entries, 0 to 11816
Data columns (total 40 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   class                          11817 non-null  object
 1   order                          11816 non-null  object
 2   family                         11817 non-null  object
 3   genus                          11817 non-null  object
 4   species                        11817 non-null  object
 5   lat                            11817 non-null  float64
 6   long                           11817 non-null  float64
 7   eventDate                      11817 non-null  object
 8   day                            11813 non-null  float64
 9   month                          11815 non-null  float64
 10  year                           11817 non-null  int64
 11  institutionCode                11800 non-null  object
 12  coordinateUncertaintyInMeters  8697 non-null   float64
 13  basisOfRecord                  11817 non-null  object
 14  individualCount                795 non-null    float64
 15  datasetKey                     11817 non-null  object
 16  ID                             11817 non-null  int64
 17  bio1                           11679 non-null  float64
 18  bio10                          11679 non-null  float64
 19  bio11                          11679 non-null  float64
 20  bio12                          11679 non-null  float64
 21  bio13                          11679 non-null  float64
 22  bio14                          11679 non-null  float64
 23  bio15                          11679 non-null  float64
 24  bio16                          11679 non-null  float64
 25  bio17                          11679 non-null  float64
 26  bio18                          11679 non-null  float64
 27  bio19                          11679 non-null  float64
 28  bio2                           11679 non-null  float64
 29  bio3                           11679 non-null  float64
 30  bio4                           11679 non-null  float64
 31  bio5                           11679 non-null  float64
 32  bio6                           11679 non-null  float64
 33  bio7                           11679 non-null  float64
 34  bio8                           11679 non-null  float64
 35  bio9                           11679 non-null  float64
 36  dist                           11668 non-null  float64
 37  dem90_hf                       11436 non-null  float64
 38  lc_class                       11396 non-null  object
 39  ndvi                           11664 non-null  float64
dtypes: float64(28), int64(2), object(10)
memory usage: 3.6+ MB
None

In [11]:
# prey.head(3)
prey.tail(3)

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
11814,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.713627,-117.551982,2017-05-28T12:28:00Z,28.0,5.0,2017,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11815,143.129761,214.728897,86.312645,703.884155,134.159149,3.000000,87.217995,382.778320,12.450000,25.301556,367.643189,138.747574,49.332005,5090.127930,301.096008,21.714203,279.381805,89.029083,207.946884,7.999103,1150.327515,grassland,6280.781738
11815,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.283060,-116.152294,2019-03-09T00:00:00Z,9.0,3.0,2019,iNaturalist,199.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11816,207.828796,298.661102,123.264259,152.645325,24.174152,0.571964,57.834797,66.522461,10.265621,23.066544,64.668320,172.413681,46.717823,6963.564941,404.882080,39.630005,365.252075,135.455856,230.889984,0.908103,324.845062,barren,925.266907
11816,Insecta,Coleoptera,Tenebrionidae,Eleodes,Eleodes acuticauda,33.598366,-117.820217,2020-05-02T10:09:00Z,2.0,5.0,2020,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11817,165.278626,211.716537,126.672401,344.240540,69.188713,1.000000,89.915398,194.495606,6.277601,11.308143,186.073731,113.556824,54.437012,3333.221680,272.416626,65.048866,207.367767,129.048874,203.714371,1.281493,186.832230,urban,4851.400000

In [12]:
prey.nunique()

class                                4
order                               14
family                              51
genus                               77
species                             80
lat                              10977
long                             10979
eventDate                        11407
day                                 31
month                               12
year                                73
institutionCode                     11
coordinateUncertaintyInMeters     1158
basisOfRecord                        2
individualCount                      3
datasetKey                          13
ID                               11817
bio1                              4122
bio10                             4180
bio11                             4138
bio12                             4211
bio13                             4201
bio14                             1395
bio15                             4147
bio16                             4211
bio17                             3181
bio18                             3774
bio19                             4208
bio2                              4197
bio3                              3303
bio4                              4211
bio5                              4190
bio6                              4191
bio7                              4210
bio8                              4169
bio9                              4181
dist                              4162
dem90_hf                          4125
lc_class                            12
ndvi                              7073
dtype: int64

In [16]:
prey.shape
prey.columns
prey.dtypes

class                             object
order                             object
family                            object
genus                             object
species                           object
lat                              float64
long                             float64
eventDate                         object
day                              float64
month                            float64
year                               int64
institutionCode                   object
coordinateUncertaintyInMeters    float64
basisOfRecord                     object
individualCount                  float64
datasetKey                        object
ID                                 int64
bio1                             float64
bio10                            float64
bio11                            float64
bio12                            float64
bio13                            float64
bio14                            float64
bio15                            float64
bio16                            float64
bio17                            float64
bio18                            float64
bio19                            float64
bio2                             float64
bio3                             float64
bio4                             float64
bio5                             float64
bio6                             float64
bio7                             float64
bio8                             float64
bio9                             float64
dist                             float64
dem90_hf                         float64
lc_class                          object
ndvi                             float64
dtype: object

## 6. Update column names 
Change the column names of institutionCode and datasetKey to institution_code and dataset_key, respectively. Make sure you’re actually updating the data frame. HINT: look for the documentation on the rename method for pandas.DataFrames.

In [20]:
# df.rename(columns={"A": "a", "B": "c"})
prey = prey.rename(columns={
    "institutionCode" : "institution_code",
    "datasetKey" : "dataset_key"
})
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11812,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.582359,-117.130409,2022-04-06T17:45:07Z,6.0,4.0,2022,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11813,168.864929,209.279877,132.899994,217.126556,43.935062,0.186721,88.170128,122.583405,3.186721,5.864936,109.776558,91.074677,51.186722,2938.296631,251.787964,75.391914,176.396042,135.899994,201.051651,1.481260,3.334348,urban,2509.291504
11813,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.235500,-117.280700,2016-04-28T06:45:00Z,28.0,4.0,2016,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11814,168.944000,217.027542,127.524216,302.635620,59.679543,1.225997,86.732315,166.990814,6.451993,12.225997,155.940826,115.709236,53.982101,3478.261719,275.912842,62.300415,213.612412,130.638260,209.373581,1.022442,95.028740,urban,3148.228271
11814,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.713627,-117.551982,2017-05-28T12:28:00Z,28.0,5.0,2017,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11815,143.129761,214.728897,86.312645,703.884155,134.159149,3.000000,87.217995,382.778320,12.450000,25.301556,367.643189,138.747574,49.332005,5090.127930,301.096008,21.714203,279.381805,89.029083,207.946884,7.999103,1150.327515,grassland,6280.781738
11815,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,33.283060,-116.152294,2019-03-09T00:00:00Z,9.0,3.0,2019,iNaturalist,199.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11816,207.828796,298.661102,123.264259,152.645325,24.174152,0.571964,57.834797,66.522461,10.265621,23.066544,64.668320,172.413681,46.717823,6963.564941,404.882080,39.630005,365.252075,135.455856,230.889984,0.908103,324.845062,barren,925.266907
11816,Insecta,Coleoptera,Tenebrionidae,Eleodes,Eleodes acuticauda,33.598366,-117.820217,2020-05-02T10:09:00Z,2.0,5.0,2020,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11817,165.278626,211.716537,126.672401,344.240540,69.188713,1.000000,89.915398,194.495606,6.277601,11.308143,186.073731,113.556824,54.437012,3333.221680,272.416626,65.048866,207.367767,129.048874,203.714371,1.281493,186.832230,urban,4851.400000

## 7. Subsetting
Complete the following subsetting tasks.

Select only the preserved specimens from prey.
Select observations between 1992 and 2000.
Select all rows for columns species and eventDate.
Select observations that are greater than 37° latitude and less than 39° latitude.

check git status -> stage changes -> check git status -> commit with message -> pull -> push changes

In [26]:
# Select only the preserved specimens from prey.

prey.columns
prey['basisOfRecord'].unique()
preserved_specimen = prey[prey['basisOfRecord'] == 'PRESERVED_SPECIMEN']
preserved_specimen

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
1679,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,34.340000,-119.410004,2016-11-29T00:00:00Z,29.0,11.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1680,154.372528,200.300980,114.870407,475.911072,108.406372,0.000000,100.069076,290.060028,2.000000,6.201149,285.269562,129.936645,57.310860,3349.972412,272.703095,47.010059,225.693039,117.870407,194.108063,0.802846,139.021927,grassland,4859.104980
1680,Insecta,Hymenoptera,Xyelidae,Xyela,Xyela concava,38.759998,-119.660004,2016-06-25T00:00:00Z,25.0,6.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1681,79.070374,170.401947,-1.718157,452.265961,73.694450,12.075387,58.115467,199.897278,44.346771,44.346771,199.846512,160.934799,44.482346,6806.624023,281.522827,-74.999733,356.522553,6.357229,170.401947,NaN,1877.535400,savanna,3379.441650
1681,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,34.290001,-119.230003,2016-11-24T00:00:00Z,24.0,11.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1682,155.460648,198.497498,118.571289,430.013184,99.510902,0.000000,99.702957,259.023773,2.000000,5.190607,255.809418,131.268570,59.336895,3137.429199,269.109345,49.446285,219.663071,120.854431,191.976440,2.306774,154.871475,closed_shrubland,3700.706543
1682,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.689999,-117.180000,2016-11-25T00:00:00Z,25.0,11.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1683,171.975601,212.391007,136.951187,251.560730,54.389912,0.463668,90.511932,151.170273,3.463668,6.463668,132.243484,82.952835,49.488071,2921.583740,251.367142,84.462578,166.904572,139.487518,203.927338,0.592433,NaN,grassland,3317.774902
1683,Insecta,Hymenoptera,Xyelidae,Xyela,Xyela concava,38.660000,-119.589996,2016-06-25T00:00:00Z,25.0,6.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1684,55.478683,142.975632,-20.735058,588.114624,94.990501,14.623221,58.780247,260.451935,53.345188,53.345188,259.053162,150.054962,43.945538,6525.333984,245.996719,-90.450348,336.447052,-13.016450,142.975632,30.419949,2300.984619,savanna,3184.269775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5412,Insecta,Coleoptera,Melolonthidae,Diplotaxis,Diplotaxis moerens,34.110900,-116.107200,2012-04-27T00:00:00Z,27.0,4.0,2012,SBMNH,NaN,PRESERVED_SPECIMEN,1.0,d883d764-4522-4928-bdf7-4d6f0aae2ebd,5413,171.401199,266.416779,86.104019,221.573486,29.183558,1.050000,47.477180,83.856628,19.667877,43.558125,83.062286,161.268433,44.769978,7136.740234,369.681122,11.829006,357.852142,97.309677,197.437500,3.703319,1053.951782,barren,1583.844360
5413,Insecta,Coleoptera,Tenebrionidae,Eleodes,Eleodes acuticauda,34.029800,-116.278400,2013-04-25T00:00:00Z,25.0,4.0,2013,SBMNH,NaN,PRESERVED_SPECIMEN,1.0,d883d764-4522-4928-bdf7-4d6f0aae2ebd,5414,142.500046,231.370560,64.690331,359.824554,54.067932,2.000000,55.887745,156.995529,30.960423,47.510422,153.355255,160.078781,46.269062,6650.139648,335.280273,-7.258590,342.538879,72.820190,205.651504,10.598809,1380.212524,open_shrubland,1651.362061
5414,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,34.250000,-119.230003,2016-11-27T00:00:00Z,27.0,11.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,5415,157.418381,194.768372,124.650002,358.096588,85.727486,0.000000,99.908348,213.793030,1.318377,2.900000,213.396591,121.732185,61.496437,2741.572998,255.578064,58.771942,196.806122,125.603561,188.242310,1.168482,26.762793,urban,3870.396973
5415,Insecta,Diptera,Syrphidae,Toxomerus,Toxomerus marginatus,32.880001,-117.250000,2013-11-16T00:00:00Z,16.0,11.0,2013,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,5416,168.143387,211.136307,132.049316,289.314026,60.962296,1.000000,89.593941,168.738327,4.000000,7.792620,151.176712,93.309196,50.802124,3073.309082,257.443085,75.971848,181.471237,134.245087,202.749741,0.543813,75.091614,urban,3601.446289
5416,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,34.290001,-119.230003,2016-12-01T00:00:00Z,1.0,12.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,5417,155.460648,198.497498,118.571289,430.013184,99.510902,0.000000,99.702957,259.023773,2.000000,5.190607,255.809418,131.268570,59.336895,3137.429199,269.109345,49.446285,219.663071,120.854431,191.976440,2.306774,154.871475,closed_shrubland,3700.706543

In [33]:
# Select observations between 1992 and 2000.

obv_92_00 = prey[prey['year'].between(1992, 2000)]
obv_92_00

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
1700,Insecta,Coleoptera,Tenebrionidae,Eleodes,Eleodes acuticauda,34.421123,-118.501387,1997-05-01T00:00:00Z,1.0,5.0,1997,UTEP,11109.0,PRESERVED_SPECIMEN,NaN,297ecc07-da20-4ebf-9f41-4f80330b4b33,1701,164.052139,233.923935,103.943611,430.573395,85.408524,1.000000,90.341942,243.386704,6.473931,14.473931,228.178177,150.136734,50.526070,5095.691895,325.297852,29.228207,296.069641,110.393616,228.634598,0.741066,429.214630,urban,2944.426025
1717,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,34.467772,-116.202715,1999-06-25T00:00:00Z,25.0,6.0,1999,UTEP,47736.0,PRESERVED_SPECIMEN,NaN,297ecc07-da20-4ebf-9f41-4f80330b4b33,1718,175.680969,273.335938,86.016029,184.159760,23.819201,1.000000,44.414768,67.621468,17.214769,38.254143,67.621468,160.409638,43.030281,7391.372070,377.030609,10.835779,366.194824,98.681000,203.801804,27.322420,965.792725,grassland,730.316284
1721,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,36.248500,-117.991028,1998-07-07T00:00:00Z,7.0,7.0,1998,UTEP,NaN,PRESERVED_SPECIMEN,NaN,297ecc07-da20-4ebf-9f41-4f80330b4b33,1722,147.054962,247.533112,52.613918,208.074432,36.672558,4.000000,66.227470,101.110840,16.957857,19.254721,100.493416,154.673431,41.000000,7639.830566,349.753693,-21.017378,370.771057,68.180321,222.533112,27.927256,1176.939453,open_shrubland,1639.310547
1732,Insecta,Orthoptera,Acrididae,Melanoplus,Melanoplus sanguinipes,38.826049,-120.108584,1998-10-11T00:00:00Z,11.0,10.0,1998,CSU,2000.0,PRESERVED_SPECIMEN,1.0,323b0e80-5e4b-4cc4-936a-d93fc8cae9bc,1733,47.266640,129.389542,-21.191164,1109.233276,189.963196,13.407290,70.784904,524.399963,57.491680,63.041679,515.479981,133.981216,43.549999,6100.312500,222.205154,-82.314064,304.519226,-10.491679,127.882248,2.310431,2385.305176,savanna,2616.363525
1734,Insecta,Orthoptera,Acrididae,Schistocerca,Schistocerca nitens,34.274568,-114.053159,1997-03-14T00:00:00Z,14.0,3.0,1997,CSU,2210.0,PRESERVED_SPECIMEN,1.0,323b0e80-5e4b-4cc4-936a-d93fc8cae9bc,1735,219.312576,323.291962,118.825050,148.716095,20.612474,1.020624,46.754322,51.566795,9.120624,33.216194,51.516796,160.712585,41.608150,8037.842773,417.879486,37.258148,380.621338,136.341949,253.241959,NaN,241.861481,open_shrubland,2594.753174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5181,Insecta,Coleoptera,Tenebrionidae,Eleodes,Eleodes acuticauda,34.700000,-120.040000,1995-07-05T00:00:00Z,5.0,7.0,1995,SBMNH,NaN,PRESERVED_SPECIMEN,1.0,d883d764-4522-4928-bdf7-4d6f0aae2ebd,5182,146.953964,199.522598,102.247345,518.502747,105.162010,0.000000,93.265343,299.939087,2.102250,9.654500,279.523407,133.795090,54.450405,3854.099609,279.199402,35.774216,243.425186,105.784576,194.647568,6.542089,417.723328,savanna,5038.578125
5182,Insecta,Coleoptera,Chrysomelidae,Diabrotica,Diabrotica undecimpunctata,34.700000,-120.040000,1995-07-05T00:00:00Z,5.0,7.0,1995,SBMNH,NaN,PRESERVED_SPECIMEN,1.0,d883d764-4522-4928-bdf7-4d6f0aae2ebd,5183,146.953964,199.522598,102.247345,518.502747,105.162010,0.000000,93.265343,299.939087,2.102250,9.654500,279.523407,133.795090,54.450405,3854.099609,279.199402,35.774216,243.425186,105.784576,194.647568,6.542089,417.723328,savanna,5038.578125
5372,Insecta,Coleoptera,Melolonthidae,Polyphylla,Polyphylla decemlineata,34.495200,-119.550000,1997-08-03T00:00:00Z,3.0,8.0,1997,SBMNH,NaN,PRESERVED_SPECIMEN,1.0,d883d764-4522-4928-bdf7-4d6f0aae2ebd,5373,137.149841,201.068802,85.693474,659.171814,141.480026,0.000000,96.419342,385.637115,2.550363,12.356922,373.392670,127.467453,49.519245,4587.774414,281.597321,25.101730,256.495575,87.895813,194.944977,7.204562,713.997253,grassland,5800.724121
5374,Insecta,Coleoptera,Melolonthidae,Polyphylla,Polyphylla decemlineata,34.463800,-119.743600,2000-06-09T00:00:00Z,9.0,6.0,2000,SBMNH,NaN,PRESERVED_SPECIMEN,1.0,d883d764-4522-4928-bdf7-4d6f0aae2ebd,5375,149.726975,197.654831,108.297424,526.453369,115.285377,0.000000,99.180885,317.866852,2.000000,7.413320,305.575043,120.276085,54.178745,3528.171631,265.641205,45.026978,220.614243,111.186615,191.586090,1.083591,229.868362,grassland,6043.500977
5408,Insecta,Coleoptera,Scarabaeidae,Canthon,Canthon simplex,33.250000,-116.770000,1998-03-15T00:00:00Z,15.0,3.0,1998,SBMNH,NaN,PRESERVED_SPECIMEN,1.0,d883d764-4522-4928-bdf7-4d6f0aae2ebd,5409,139.206131,217.035629,73.498398,569.850281,101.791542,2.832059,78.627884,297.992554,26.496178,39.943607,278.701721,150.966888,48.262878,5669.671875,314.742218,6.163673,308.578522,80.834282,188.720017,0.522245,949.128784,closed_shrubland,4451.394043

In [41]:
# Select all rows for columns species and eventDate.

spp_event = prey.loc[:,('species', 'eventDate')]
spp_event

# another way to do this: 

prey[['species', 'eventDate']]

                     species             eventDate
0        Sympetrum corruptum  2020-09-29T08:24:00Z
1      Armadillidium vulgare  2021-12-04T14:49:59Z
2        Bombus vosnesenskii  2021-06-18T08:52:00Z
3             Apis mellifera  2016-04-17T09:28:00Z
4       Oncopeltus fasciatus  2019-04-06T18:44:31Z
...                      ...                   ...
11812         Apis mellifera  2022-04-06T17:45:07Z
11813  Armadillidium vulgare  2016-04-28T06:45:00Z
11814         Vanessa cardui  2017-05-28T12:28:00Z
11815         Vanessa cardui  2019-03-09T00:00:00Z
11816     Eleodes acuticauda  2020-05-02T10:09:00Z

[11817 rows x 2 columns]

In [ ]:
# Select observations that are greater than 37° latitude and less than 39° latitude.

In [46]:
prey_37_39 = prey[prey['lat'].between(37,39)]
prey_37_39

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
5,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,37.842187,-122.272478,2020-05-02T10:28:25Z,2.0,5.0,2020,iNaturalist,917.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,6,144.511795,178.412857,105.581818,565.076050,122.171043,1.000000,87.983589,308.378662,7.063087,9.205670,308.378662,89.164856,51.079494,2885.461670,234.265152,60.451580,173.813568,105.581818,172.760529,0.365533,35.971046,urban,3031.351807
9,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,37.323517,-122.174308,2019-04-29T15:22:16Z,29.0,4.0,2019,iNaturalist,5.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,10,131.805481,181.386352,89.509621,824.623535,164.044968,2.000000,86.375435,431.711121,11.555281,15.646415,431.711121,118.941368,54.445618,3672.007080,252.594223,35.436752,217.157471,89.509621,176.914505,1.444703,532.485596,evergreen_needleleaf,7056.129395
10,Insecta,Lepidoptera,Sphingidae,Hyles,Hyles lineata,38.412833,-121.421913,2020-03-27T07:12:56Z,27.0,3.0,2020,iNaturalist,65.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11,158.215454,229.449997,82.928772,436.710846,94.928772,1.000000,86.713325,231.857544,6.000000,10.000000,231.857544,142.071228,46.286674,5830.274902,334.665436,30.430893,304.234558,82.928772,229.215454,2.179459,8.622081,urban,3572.570801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11799,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.541326,-122.268321,2020-04-26T14:46:13Z,26.0,4.0,2020,iNaturalist,28388.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11800,142.545090,182.881439,99.324318,511.431885,109.029114,1.059186,88.170654,273.413452,6.177559,9.062639,273.413452,99.163254,52.468727,3257.272217,235.395645,48.043705,187.351944,99.324318,179.136810,1.211238,9.270312,urban,3299.270996
11800,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,38.152413,-122.573731,2018-04-01T10:29:00Z,1.0,4.0,2018,iNaturalist,104.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11801,140.896484,188.304077,90.547089,783.829834,181.144150,1.000000,93.849670,450.759644,7.907309,11.675732,450.759644,129.369583,54.954678,3874.465088,268.564911,36.011116,232.553802,90.547089,184.949127,1.142068,44.774391,grassland,4599.227539
11803,Insecta,Odonata,Coenagrionidae,Ischnura,Ischnura cervula,37.891591,-122.003384,2013-03-30T13:50:00Z,30.0,3.0,2013,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11804,147.000000,201.407883,90.781387,508.146759,107.127304,1.000000,86.392433,268.328735,6.000000,9.442434,268.328735,123.065445,50.586910,4336.548828,278.712585,37.203167,241.509415,90.781387,197.378540,4.003264,147.056702,grassland,4603.566895
11804,Insecta,Coleoptera,Melolonthidae,Polyphylla,Polyphylla decemlineata,37.584329,-121.688900,2020-08-10T08:26:53Z,10.0,8.0,2020,iNaturalist,95.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11805,147.185547,219.315170,82.798744,513.579102,99.849487,1.214599,83.629662,263.451080,7.568087,12.741916,263.451080,142.280304,47.728756,5418.041992,321.272797,25.848595,295.424194,82.798744,216.292755,12.225791,461.055420,savanna,4144.618164
11810,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,37.158425,-121.780997,2022-03-13T15:49:39Z,13.0,3.0,2022,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11811,144.861984,202.004623,91.072861,656.618042,137.391312,1.550000,89.449997,353.130402,6.884505,12.884505,353.130402,142.147263,53.000000,4389.426270,293.429016,27.049231,266.379791,91.072861,199.262756,7.531013,279.729614,woody_savanna,6042.207520