# Discussion Section 2: Water conflicts in the Colorado River Basin

This discussion section will guide you through exploring data about water-related conflicts at the Colorado River Basin using data from the U.S. Geological Survey (USGS). In this discussion section, you will:

- Practice version control using git via the terminal
- Use methods to work with pandas.Series of strings using the .str accessor
- Practice method chaining

## Archive Exploration
This dataset catalogues events in the Colorado River Basin (particularly the Upper Colorado River Basin in most cases) from 2005 - 2021. The data were collected to catalogue and understand water-related conflicts in the Colorado River Basin. 

**Citation:** Holloman, D.V., Hines, M.K., and Zoanni, D.K., 2023, Coded Water Conflict and Crisis Events in the Colorado River Basin, Derived from LexisNexis search 2005-2021: U.S. Geological Survey data release, https://doi.org/10.5066/P9X6WR7J.
**Date of access:** October 7, 2026
**Link:** https://www.sciencebase.gov/catalog/item/63acac09d34e92aad3ca1480

## Data loading

In [1]:
# Load packages
import pandas as pd
import os
import numpy as np

# Import data
fp = os.path.join('data', 'Colorado_River_Basin_Water_Conflict_Table.csv')
df = pd.read_csv(fp)

## Preliminary Data Exploration

In [2]:
# Explore the data
pd.set_option('display.max_columns', None)
print(df.shape)
print(df.info())

(268, 48)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Event                                         268 non-null    int64
 1   Search Source                                 268 non-null    object
 2   Newspaper                                     268 non-null    object
 3   Article Title                                 268 non-null    object
 4   Duplicate                                     267 non-null    object
 5   Report Date                                   267 non-null    object
 6   Report Year                                   265 non-null    float64
 7   Event Date                                    248 non-null    object
 8   Event Day                                     18 non-null     float64
 9   Event Month                                   212 non-null    float64
 10  Event Year                                    257 non-null    float64
 11  Conflict Present                              252 non-null    object
 12  Crisis Present                                254 non-null    object
 13  Basin                                         250 non-null    object
 14  HUC6                                          110 non-null    object
 15  HUC2                                          250 non-null    object
 16  Place                                         254 non-null    object
 17  County                                        8 non-null      object
 18  County FIPS                                   8 non-null      float64
 19  State                                         178 non-null    object
 20  State FIPS                                    178 non-null    object
 21  Urban or Rural                                254 non-null    object
 22  Issue Type                                    255 non-null    object
 23  Event Summary                                 256 non-null    object
 24  Stakeholders                                  255 non-null    object
 25  Intensity Value                               255 non-null    float64
 26  Comments                                      190 non-null    object
 27  Related Observation Themes                    86 non-null     object
 28  Article Text Search - water quality           268 non-null    int64
 29  Article Text Search - invasive species        268 non-null    int64
 30  Article Text Search - conservation            268 non-null    int64
 31  Article Text Search - drought                 268 non-null    int64
 32  Article Text Search - flood                   268 non-null    int64
 33  Article Text Search - ground water depletion  268 non-null    int64
 34  Article Text Search - depletion               268 non-null    int64
 35  Article Text Search - infrastructure          268 non-null    int64
 36  Article Text Search - fish passage            268 non-null    int64
 37  Article Text Search - instream water rights   268 non-null    int64
 38  Article Text Search - water rights            268 non-null    int64
 39  Article Text Search - intergovernmental       268 non-null    int64
 40  Article Text Search - water transfers         268 non-null    int64
 41  Article Text Search - navigation              268 non-null    int64
 42  Article Text Search - fish                    268 non-null    int64
 43  Article Text Search - invasive                268 non-null    int64
 44  Article Text Search - diversion               268 non-null    int64
 45  Article Text Search - water diversion         268 non-null    int64
 46  Article Text Search - instream                268 non-null    int64
 47  Article Text Search - aquatic                 268 non-null    int64
dtypes: float64(6), int64(21), object(21)
memory usage: 100.6+ KB
None

In [3]:
# Show the first few rows of the data
df.head()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,2021.0,N,Y,Lower Colorado,150301,15,Colorado River Indian Reservation,NaN,NaN,NaN,NaN,Rural,Water rights more generally,The Colorado River Indian Tribes Water Resilie...,"Colorado River Indian Tribes, State Government...",3.0,"Event is proposal of the bill, preliminary agr...",NaN,0,0,2,6,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,2021.0,Y,Y,Upper San Juan,140801,14,Southern Ute Indian Reservation,NaN,NaN,NaN,NaN,Rural,Intergovernmental issues,State and federal officials say that Tribal Na...,"Sothern Ute Indian Tribe, Ute Mountain Tribe, ...",-1.0,Interaction between tribal nations and state/f...,Lack of tribal representation,0,0,2,6,0,0,0,7,0,0,18,0,0,0,0,0,0,0,0,0

In [4]:
# List the columns
df.columns

Index(['Event', 'Search Source', 'Newspaper', 'Article Title', 'Duplicate',
       'Report Date', 'Report Year', 'Event Date', 'Event Day', 'Event Month',
       'Event Year', 'Conflict Present', 'Crisis Present', 'Basin', 'HUC6',
       'HUC2', 'Place', 'County', 'County FIPS', 'State', 'State FIPS',
       'Urban or Rural', 'Issue Type', 'Event Summary', 'Stakeholders',
       'Intensity Value', 'Comments', 'Related Observation Themes',
       'Article Text Search - water quality',
       'Article Text Search - invasive species',
       'Article Text Search - conservation', 'Article Text Search - drought',
       'Article Text Search - flood',
       'Article Text Search - ground water depletion',
       'Article Text Search - depletion',
       'Article Text Search - infrastructure',
       'Article Text Search - fish passage',
       'Article Text Search - instream water rights',
       'Article Text Search - water rights',
       'Article Text Search - intergovernmental',
       'Article Text Search - water transfers',
       'Article Text Search - navigation', 'Article Text Search - fish',
       'Article Text Search - invasive', 'Article Text Search - diversion',
       'Article Text Search - water diversion',
       'Article Text Search - instream', 'Article Text Search - aquatic'],
      dtype='object')

In [5]:
# Define types
df.dtypes

Event                                             int64
Search Source                                    object
Newspaper                                        object
Article Title                                    object
Duplicate                                        object
Report Date                                      object
Report Year                                     float64
Event Date                                       object
Event Day                                       float64
Event Month                                     float64
Event Year                                      float64
Conflict Present                                 object
Crisis Present                                   object
Basin                                            object
HUC6                                             object
HUC2                                             object
Place                                            object
County                                           object
County FIPS                                     float64
State                                            object
State FIPS                                       object
Urban or Rural                                   object
Issue Type                                       object
Event Summary                                    object
Stakeholders                                     object
Intensity Value                                 float64
Comments                                         object
Related Observation Themes                       object
Article Text Search - water quality               int64
Article Text Search - invasive species            int64
Article Text Search - conservation                int64
Article Text Search - drought                     int64
Article Text Search - flood                       int64
Article Text Search - ground water depletion      int64
Article Text Search - depletion                   int64
Article Text Search - infrastructure              int64
Article Text Search - fish passage                int64
Article Text Search - instream water rights       int64
Article Text Search - water rights                int64
Article Text Search - intergovernmental           int64
Article Text Search - water transfers             int64
Article Text Search - navigation                  int64
Article Text Search - fish                        int64
Article Text Search - invasive                    int64
Article Text Search - diversion                   int64
Article Text Search - water diversion             int64
Article Text Search - instream                    int64
Article Text Search - aquatic                     int64
dtype: object

## Location columns

In [18]:
df['Conflict Present'].value_counts()

Conflict Present
Y    145
N    107
Name: count, dtype: int64

# String accessor for pandas.Series

In [6]:
# Example series
s = pd.Series(['California; Nevada', 'Arizona', np.nan, 'Nevada; Utah'])
s

0    California; Nevada
1               Arizona
2                   NaN
3          Nevada; Utah
dtype: object

In [7]:
# CELL 2
# str accessor (doesn't do anything by itself)
s.str

In [8]:
# CELL 3
# Use str accessor with additional methods to perform string operations
s.str.split(';')

0    [California,  Nevada]
1                [Arizona]
2                      NaN
3          [Nevada,  Utah]
dtype: object

In [9]:
# CELL 4
s.str.split(';').explode()

0    California
0        Nevada
1       Arizona
2           NaN
3        Nevada
3          Utah
dtype: object

## Examine state codes

In [25]:
df['State'].value_counts()

State
AZ                            66
CO                            34
UT                            27
NV                            10
CA                             7
NM                             6
AZ; CA                         4
AZ; UT                         3
AZ; CA; CO; NV; NM; UT; WY     3
AZ; NV                         2
NV; AZ                         2
CO; AZ                         2
CO; UT; WY; NM                 2
AZ; NM                         1
CA; NV; AZ                     1
WY; UT; CO                     1
UT; CO; WY                     1
CO; WY                         1
AZ; CA; NV                     1
UT; AZ                         1
AZ; CO; NM; UT                 1
OH; UT                         1
TX                             1
Name: count, dtype: int64

In [24]:
df['State'].str.split(';').explode().value_counts()

State
AZ     81
CO     39
UT     29
NV     12
 UT    11
CA      8
 CA     8
 NM     7
 NV     7
 WY     7
 CO     6
 AZ     6
NM      6
OH      1
WY      1
TX      1
Name: count, dtype: int64

In [32]:
df['State'].isna().value_counts()
# 90 NAs

State
False    178
True      90
Name: count, dtype: int64

In [50]:
df2 = df[['State', 'Conflict Present']]
df2 = df2.loc[df2['State'].notna()]
df2 = df2[df2['Conflict Present'] == 'Y']
df2

      State Conflict Present
0        CO                Y
1        CO                Y
5        AZ                Y
11   OH; UT                Y
12       UT                Y
..      ...              ...
255      UT                Y
257      AZ                Y
258      UT                Y
262      AZ                Y
265  AZ; CA                Y

[98 rows x 2 columns]

In [53]:
# Exploratory wrangling

states_unique = df.loc[df['Conflict Present'] == 'Y', 'State'].str.split(';').explode().unique()

states_unique

array(['CO', nan, 'AZ', 'OH', ' UT', 'UT', 'CA', ' NV', ' WY', ' NM',
       ' CA', 'NV', ' AZ', ' CO', 'NM', 'WY'], dtype=object)

In [58]:
df_conflict = df.loc[df['Conflict Present'] == 'Y'].copy()
df_conflict['State'] = df_conflict['State'].str.split(';')
df_explode = df_conflict.explode('State')
df_explode

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,2021.0,Y,Y,Upper San Juan,140801,14,Southern Ute Indian Reservation,NaN,NaN,NaN,NaN,Rural,Intergovernmental issues,State and federal officials say that Tribal Na...,"Sothern Ute Indian Tribe, Ute Mountain Tribe, ...",-1.0,Interaction between tribal nations and state/f...,Lack of tribal representation,0,0,2,6,0,0,0,7,0,0,18,0,0,0,0,0,0,0,0,0
5,6,USGS1-50.docx,The Arizona Republic (Phoenix),Everyone loses if we cannot agree on how we us...,False,22-Apr-17,2017.0,NaN,NaN,4.0,2017.0,Y,Y,Entire Lower Colorado Basin,NaN,15,State of Arizona,NaN,NaN,AZ,4,Both,Intergovernmental issues,Water management agencies are in a legal dispu...,"Water Managers, All Water Users, Conservation ...",2.0,Event is delays in negotiations between state/...,NaN,0,0,10,11,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
7,8,USGS1-50.docx,"Navajo Times (Window Rock, Arizona)","Colorado River, stolen by law; Indigenous nati...",False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15",Entire Colorado River Basin,NaN,NaN,NaN,NaN,Both,Intergovernmental issues,"Amidst ongoing drought, the Colorado River Ind...","Colorado River Indian Tribes, State Government...",2.0,Although the article focuses quite a bit on hi...,NaN,0,0,0,4,0,0,0,6,0,0,15,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,259,USGS301-350.docx,The Salt Lake Tribune,Alder: A new set of negotiations need for The ...,False,29-Aug-08,2008.0,8,NaN,8.0,2008.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15",Utah,NaN,NaN,UT,49,Both,Intergovernmental issues,An op ed written by the Associate Dean for Aca...,"State Government, Federal Government, Environm...",-1.0,Event is letter written by dean disputing comm...,NaN,0,0,0,1,0,0,0,0,0,0,4,0,0,0,2,0,0,0,2,0
260,261,USGS301-350.docx,Farmington Daily Times (New Mexico),Experts predict low San Juan County river flow...,False,11-Apr-15,2015.0,4,NaN,4.0,2015.0,Y,Y,Lower San Juan,140802,14,San Juan River,NaN,NaN,NaN,NaN,Both,Drought,The Colorado Basin River Forecast Center predi...,"Navajo Nation, State Government, Water Manager...",-1.0,Event is release of forecast which prompts wat...,Devaluing tribal land and resources,0,0,1,4,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0
262,263,USGS301-350.docx,Associated Press State & Local,Officials: Arizona will miss US deadline for k...,False,20-Feb-19,2019.0,2/19/2019,19.0,2.0,2019.0,Y,Y,Entire Lower Colorado Basin,NaN,15,State of Arizona,NaN,NaN,AZ,4,Both,Conservation; Water rights more generally,The state of Arizona announced they won't have...,"State Government, Federal Government, All Wate...",-2.0,Scored a -2 based on the disagreements among t...,Inequitable government access/relationship,0,0,0,6,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,2019.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15","State of Arizona, State of California",NaN,NaN,AZ,04; 06,Both,Intergovernmental issues,The event is that California's Imperial Irriga...,"All Water Users, Agriculture, State Government...",-4.0,Scored based on the fact that the event is act...,NaN,1,0,3,9,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,2019.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15","State of Arizona, State of California",NaN,NaN,CA,04; 06,Both,Intergovernmental issues,The event is that California's Imperial Irriga...,"All Water Users, Agriculture, State Government...",-4.0,Scored based on the fact that the event is act...,NaN,1,0,3,9,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0